name: Projeto2020
favicon: null
layout_spectrum: 0.90257
typography_spectrum: 0.96272
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1d6c2'
    - '#514120'
    - '#8f7c5e'
    - '#ae9a81'
    - '#cdbea7'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.0625
  rhythmicContrast: 0.20726265502162278
purpose: []
